# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_auto_20180115_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default=1, error_messages={'null': '不能为空'}, max_length=32),
            preserve_default=False,
        ),
    ]
